// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPractica2Ti.Models;

public partial class Imagene
{
    public int IdImagen { get; set; }

    public string NombreArchivo { get; set; }

    public int? Tamanio { get; set; }

    public string TipoDeContenido { get; set; }

    public string RutaArchivo { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();
}